import {
  spfOne,
  spfTwo,
  spfThree,
  spfFour,
  bestSellerOne,
  bestSellerTwo,
  bestSellerThree,
  bestSellerFour,
  newArrOne,
  newArrTwo,
  newArrThree,
  newArrFour,
} from "../assets/images/index";

// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Shop",
    link: "/shop",
  },
  {
    _id: 1003,
    title: "About",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Contact",
    link: "contact",
  },
  {
    _id: 1005,
    title: "Journal",
    link: "/journal",
  },
];
// =================== NavBarList End here ======================
// =================== Special Offer data Start here ============
export const SplOfferData = [
  {
    _id: "201",
    img: spfOne,
    productName: "Brazillian Hair",
    price: "350000",
    color: "Black",
    badge: true,
    des: "18 Inch Hair Lace Front Wave Wigs",
  },
  {
    _id: "202",
    img: newArrFour,
    productName: "Human Hair",
    price: "180000",
    color: "Gray",
    badge: true,
    des: "18 Inch Hair Lace Front Wave Wigs",
  },
  {
    _id: "203",
    img: spfThree,
    productName: "Brazillian Hair",
    price: "250000",
    color: "Brown",
    badge: true,
    des: "18 Inch Hair Lace Front Wave Wigs",
  },
  {
    _id: "204",
    img: spfFour,
    productName: "Human Hair",
    price: "220000",
    color: "Black",
    badge: true,
    des: "18 Inch Hair Lace Front Wave Wigs",
  },
];
// =================== Special Offer data End here ==============

// =================== PaginationItems Start here ===============

export const paginationItems = [
  {
    _id: 1001,
    img: spfOne,
    productName: "Human Hair",
    price: "350000",
    color: "Black",
    badge: true,
    des: "18 Inch Hair Lace Front Wave Wigs",
  },
  {
    _id: 1002,
    img: spfTwo,
    productName: "Peruzzian Hair",
    price: "180000",
    color: "Gray",
    badge: true,
    des: "18 Inch Hair Lace Front Wave Wigs",
  },
  {
    _id: 1003,
    img: spfThree,
    productName: "Human Hair",
    price: "250000",
    color: "Brown",
    badge: true,
    des: "18 Inch Hair Lace Front Wave Wigs",
  },
  {
    _id: 1004,
    img: spfFour,
    productName: "Human Hair",
    price: "22000",
    color: "Black",
    badge: true,
    des: "18 Inch Hair Lace Front Wave Wigs",
  },
  {
    _id: 1005,
    img: bestSellerOne,
    productName: "Brazillian Hair",
    price: "35000",
    color: "Black",
    badge: true,
    des: "18 Inch Hair Lace Front Wave Wigs",
  },
  {
    _id: 1006,
    img: bestSellerTwo,
    productName: "Perruvian Hair",
    price: "180000",
    color: "Gray",
    badge: false,
    des: "18 Inch Hair Lace Front Wave Wigs",
  },
  {
    _id: 1007,
    img: bestSellerThree,
    productName: "Human Hair",
    price: "250000",
    color: "Brown",
    badge: true,
    des: "18 Inch Hair Lace Front Wave Wigs",
  },
  {
    _id: 1008,
    img: bestSellerFour,
    productName: "Human Hair",
    price: "220000",
    color: "Black",
    badge: false,
    des: "18 Inch Hair Lace Front Wave Wigs",
  },
  {
    _id: 1009,
    img: newArrOne,
    productName: "Brazillian Hair",
    price: "440000",
    color: "Black",
    badge: true,
    des: "18 Inch Hair Lace Front Wave Wigs",
  },
  {
    _id: 1010,
    img: newArrTwo,
    productName: "Human Hair",
    price: "250000",
    color: "Black",
    badge: true,
    des: "18 Inch Hair Lace Front Wave Wigs",
  },
  {
    _id: 1011,
    img: newArrThree,
    productName: "Perruvian Hair",
    price: "80000",
    color: "Brown",
    badge: true,
    des: "18 Inch Hair Lace Front Wave Wigs",
  },
  {
    _id: 1012,
    img: newArrFour,
    productName: "Human Hair",
    price: "60000",
    color: "Brown",
    badge: false,
    des: "18 Inch Hair Lace Front Wave Wigs",
  },
  {
    _id: 1013,
    img: newArrTwo,
    productName: "Human Hair",
    price: "60000",
    color: "Brown",
    badge: false,
    des: "18 Inch Hair Lace Front Wave Wigs",
  },

  {
    _id: 1014,
    img: newArrTwo,
    productName: "Human Hair",
    price: "250000",
    color: "Black",
    badge: true,
    des: "18 Inch Hair Lace Front Wave Wigs",
  },
  {
    _id: 1015,
    img: newArrFour,
    productName: "Human Hair",
    price: "60000",
    color: "Brown",
    badge: false,
    des: "18 Inch Hair Lace Front Wave Wigs",
  },
  {
    _id: 1016,
    img: newArrTwo,
    productName: "Human Hair",
    price: "250000",
    color: "Black",
    badge: true,
    des: "18 Inch Hair Lace Front Wave Wigs",
  },
  {
    _id: 1017,
    img: bestSellerFour,
    productName: "Human Hair",
    price: "220000",
    color: "Black",
    badge: false,
    des: "18 Inch Hair Lace Front Wave Wigs",
  },
  {
    _id: 1018,
    img: newArrOne,
    productName: "Brazillian Hair",
    price: "440000",
    color: "Black",
    badge: true,
    des: "18 Inch Hair Lace Front Wave Wigs",
  },
  {
    _id: 1019,
    img: newArrTwo,
    productName: "Human Hair",
    price: "250000",
    color: "Black",
    badge: true,
    des: "18 Inch Hair Lace Front Wave Wigs",
  },
  {
    _id: 1020,
    img: newArrThree,
    productName: "Perruvian Hair",
    price: "80000",
    color: "Brown",
    badge: true,
    des: "18 Inch Hair Lace Front Wave Wigs",
  },
  {
    _id: 1021,
    img: spfThree,
    productName: "Human Hair",
    price: "250000",
    color: "Brown",
    badge: true,
    des: "18 Inch Hair Lace Front Wave Wigs",
  },
  {
    _id: 1022,
    img: spfFour,
    productName: "Peruvian Hair",
    price: "220000",
    color: "Black",
    badge: true,
    des: "18 Inch Hair Lace Front Wave Wigs",
  },
  {
    _id: 1023,
    img: bestSellerOne,
    productName: "Brazillian Hair",
    price: "350000",
    color: "Black",
    badge: true,
    des: "18 Inch Hair Lace Front Wave Wigs",
  },
  {
    _id: 1024,
    img: spfOne,
    productName: "Human Hair",
    price: "350000",
    color: "Black",
    badge: true,
    des: "18 Inch Hair Lace Front Wave Wigs",
  },
  {
    _id: 1025,
    img: spfTwo,
    productName: "Brazillian Hair",
    price: "180000",
    color: "Gray",
    badge: true,
    des: "18 Inch Hair Lace Front Wave Wigs",
  },
  {
    _id: 1026,
    img: spfThree,
    productName: "Human Hair",
    price: "250000",
    color: "Brown",
    badge: true,
    des: "18 Inch Hair Lace Front Wave Wigs",
  },
  {
    _id: 1027,
    img: spfFour,
    productName: "Peruvian Hair",
    price: "220000",
    color: "Black",
    badge: true,
    des: "18 Inch Hair Lace Front Wave Wigs",
  },
  {
    _id: 1028,
    img: bestSellerOne,
    productName: "Brazillian Hair",
    price: "350000",
    color: "Black",
    badge: true,
    des: "18 Inch Hair Lace Front Wave Wigs",
  },
  {
    _id: 1029,
    img: bestSellerTwo,
    productName: "Perruvian Hair",
    price: "180000",
    color: "Gray",
    badge: false,
    des: "18 Inch Hair Lace Front Wave Wigs",
  },
  {
    _id: 1030,
    img: bestSellerThree,
    productName: "Human Hair",
    price: "250000",
    color: "Brown",
    badge: true,
    des: "18 Inch Hair Lace Front Wave Wigs",
  },
  {
    _id: 1031,
    img: bestSellerFour,
    productName: "Human Hair",
    price: "220000",
    color: "Black",
    badge: false,
    des: "18 Inch Hair Lace Front Wave Wigs",
  },
  {
    _id: 1032,
    img: newArrOne,
    productName: "Brazillian Hair",
    price: "440000",
    color: "Black",
    badge: true,
    des: "18 Inch Hair Lace Front Wave Wigs",
  },
  {
    _id: 1033,
    img: newArrTwo,
    productName: "Human Hair",
    price: "250000",
    color: "Black",
    badge: true,
    des: "18 Inch Hair Lace Front Wave Wigs",
  },
  {
    _id: 1034,
    img: newArrThree,
    productName: "Perruvian Hair",
    price: "80000",
    color: "Brown",
    badge: true,
    des: "18 Inch Hair Lace Front Wave Wigs",
  },
  {
    _id: 1035,
    img: newArrFour,
    productName: "Human Hair",
    price: "60000",
    color: "Brown",
    badge: false,
    des: "18 Inch Hair Lace Front Wave Wigs",
  },
  {
    _id: 1036,
    img: newArrTwo,
    productName: "Human Hair",
    price: "60000",
    color: "Brown",
    badge: false,
    des: "18 Inch Hair Lace Front Wave Wigs",
  },
  {
    _id: 1037,
    img: newArrFour,
    productName: "Human Hair",
    price: "60000",
    color: "Brown",
    badge: false,
    des: "18 Inch Hair Lace Front Wave Wigs",
  },
  {
    _id: 1038,
    img: newArrTwo,
    productName: "Human Hair",
    price: "250000",
    color: "Black",
    badge: true,
    des: "18 Inch Hair Lace Front Wave Wigs",
  },
  {
    _id: 1039,
    img: bestSellerFour,
    productName: "Human Hair",
    price: "220000",
    color: "Black",
    badge: false,
    des: "18 Inch Hair Lace Front Wave Wigs",
  },
  {
    _id: 1040,
    img: newArrOne,
    productName: "Brazillian Hair",
    price: "440000",
    color: "Black",
    badge: true,
    des: "18 Inch Hair Lace Front Wave Wigs",
  },
  {
    _id: 1041,
    img: newArrTwo,
    productName: "Human Hair",
    price: "250000",
    color: "Black",
    badge: true,
    des: "18 Inch Hair Lace Front Wave Wigs",
  },
  {
    _id: 1042,
    img: newArrThree,
    productName: "Perruvian Hair",
    price: "80000",
    color: "Brown",
    badge: true,
    des: "18 Inch Hair Lace Front Wave Wigs",
  },
  {
    _id: 1043,
    img: spfThree,
    productName: "Human Hair",
    price: "250000",
    color: "Brown",
    badge: true,
    des: "18 Inch Hair Lace Front Wave Wigs",
  },
  {
    _id: 1044,
    img: spfFour,
    productName: "Peruvian Hair",
    price: "220000",
    color: "Black",
    badge: true,
    des: "18 Inch Hair Lace Front Wave Wigs",
  },
  {
    _id: 1045,
    img: bestSellerOne,
    productName: "Brazillian Hair",
    price: "350000",
    color: "Black",
    badge: true,
    des: "18 Inch Hair Lace Front Wave Wigs",
  },
  {
    _id: 1046,
    img: spfOne,
    productName: "Human Hair",
    price: "350000",
    color: "Black",
    badge: true,
    des: "18 Inch Hair Lace Front Wave Wigs",
  },
];
// =================== PaginationItems End here =================
